### ISSUE TITLE
A simple example of requiring just html templates with something like stringify

### ISSUE THREAD

**Issue by latentflip** [AmpersandJS/examples#17]
If you're using bindings, you don't need anything more than straight up html for templates, so something like: https://github.com/JohnPostlethwait/stringify makes this really easy to just require templates directly from a view.

This just came up in gitter, so a simple example of this would be useful, assigning to me, unless anyone else wants to do it @CrowdHailer?

**Comment by CrowdHailer** [comment]
I am still learning ampersand so an example from me could be a bit misleading(rookie errors). However I have a clear weekend so will try put something together then.
