### ISSUE TITLE
What's the purpose of the internals object?

### ISSUE THREAD

**Issue by minustime** [AmpersandJS/examples#9]
Thanks for sharing these patterns. I've seen the `internals` object in a few hapijs projects. Is the `internals` object's purpose just to encapsulate application level code?

**Comment by fyockm** [comment]
To my understanding, `internals` is a way to use client cookies to persist a state across multiple requests. For more info, see http://hapijs.com/api#serverstatename-options

**Comment by geek** [comment]
@minustime are you referring to this coding style: https://github.com/hapijs/hapi/blob/master/lib/auth.js#L8-L10 ???

**Comment by minustime** [comment]
Hey @geek yup, I saw it in the hapi.js code first, then on some plugins and now here https://github.com/AmpersandJS/examples/blob/master/hapi-hbs/server.js#L8 so I was curious of the significance of the object.

**Comment by geek** [comment]
@minustime our style guide talks about it here: http://hapijs.com/styleguide#user-content-module-globals

Its actually really handy when you get used to it, makes it easier to identify any scope leaks in a module.  But I prefer it for this line when declaring a constructor:

```js
module.exports = internals.Server = function (options) {
```

Compare that to this style

```js
var Server = function () {
...
};

module.exports = Server;
```

Keep in mind that we also avoid hoisted functions.

**Comment by minustime** [comment]
Got it. I don't think I came across that style guide before, thanks for the explanation and the link.

**Comment by fyockm** [comment]
@geek thanks for jumping in to explain.
